version: '3'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analysis
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=ja_JP.UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
